spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:31012/agence}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456Aa}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
server:
  port: 6161

app:
  security:
    admin-email: admin
    admin-password: admin

