spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/colispro}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
server:
  port: 8080

app:
  security:
    admin-email: admin@colispro.local
    admin-password: admin123

